# Configuracion del Microservicio
spring:
  application:
    name: api-similars-products

# Configuracion server
server:
  port: 5000
  error:    include-message: always
    include-exception: true
    
# Configuracion Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Configuracion de la API de Productos Similares
existing-apis:
  name: existingApis
  url:
    base: http://localhost:3001
    product: /product/{productId}
    similarids: /product/{productId}/similarids